### PR TITLE
Fix the warning notifications

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Updated the annotation extension to use `p-notification--caution` instead of the deprecated `p-notificaiton--warning`.

## QA
- In master branch, open `docs/en/index.md`
- Add the line:
``` markdown
!!! Warning:
    A machine destined for MAAS will have its disk space overwritten.


!!! Information:
    Some information
```
- Run:
``` bash
python3 -m venv env3 && source env3/bin/activate  # Create encapsulated environment
pip install -e .  # Install the module in editable mode

documentation-builder --source-folder docs  # build the documentation-builder's own documentation
xdg-open build/en/index.html  # Open up the documentation page
```
- See that the warning is not styled
- See that there is no information notifications
- Check out this branch
- Run `documentation-builder --source-folder docs`
- Refresh the docs page and see the notification is styled

### CODE REVIEW

**Comment by evilnick** [comment]
@anthonydillon apparently my review doesn't count, and I can't even change the labels, but this works for me

**Comment by anthonydillon** [comment]
Added the information annotation styling.

**Comment by anthonydillon** [comment]
Added the information annotation styling.

**Comment by anthonydillon** [comment]
@evilnick you should have all the rights now.

**Comment by evilnick** [comment]
image

**Comment by anthonydillon** [comment]
I can bump the version. @evilnick do the annotations all work in this branch?

**Comment by evilnick** [comment]
No, that sshot above is from this branch. i think Warnings worked, but when you added 'information' it stopped working again

**Comment by anthonydillon** [comment]
Odd, working locally for me.

**Comment by anthonydillon** [comment]
This is what I see:
screenshot-2018-6-1 getting started with documentation-builder documentation for documentation-builder

**Comment by evilnick** [comment]
Hmm, okay, I'll pull it again
If it works i'll just merge it

**Comment by anthonydillon** [comment]
@evilnick your the best!

**Comment by evilnick** [comment]
Ok, yes it seems good :+1:

**Comment by pmatulis** [comment]
What about "Important"?

**Pull request merged**
